name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true # Força o fim do warning de Node

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Versão específica para evitar conflitos
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (git commit -m "docs: update daily quote" && git push)
