name: Update README
on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4 # Atualizado!
      - name: Setup Python
        uses: actions/setup-python@v5 # Atualizado!
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Run script
        run: python update_readme.py
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          # O commit só acontece se houver mudança real, evitando loops
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: update daily quote"
          git push
